# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bun" # See documentation for possible values (use npm otherwise)
    directories:
      - "/"
      - "/apps/app"
      - "/apps/docs"
      - "/apps/marketing"
      - "/apps/waitlist"
      - "/packages/__example__"
      - "/packages/analytics"
      - "/packages/async-state"
      - "/packages/config"
      - "/packages/crypto"
      - "/packages/errors"
      - "/packages/fonts"
      - "/packages/next-config"
      - "/packages/orpc"
      - "/packages/pwa"
      - "/packages/rpc"
      - "/packages/security"
      - "/packages/seo"
      - "/packages/shadcn"
      - "/packages/typescript-config"
      - "/packages/ui"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
