packages:
  - apps/*
  - packages/*
  - configs/*

catalog:
  '@biomejs/biome': 2.3.0
  '@bprogress/next': ^3.2.12
  '@changesets/cli': ^2.29.7
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@neondatabase/serverless': ^1.0.2
  '@next/bundle-analyzer': ^15.5.4
  '@next/mdx': ^15.5.4
  '@orpc/client': ^1.10.0
  '@orpc/react-query': ^1.10.0
  '@orpc/server': ^1.10.0
  '@playwright/test': ^1.50.3
  '@polar-sh/better-auth': ^1.1.11
  '@radix-ui/react-slot': ^1.2.3
  '@t3-oss/env-core': ^0.13.8
  '@t3-oss/env-nextjs': ^0.13.8
  '@tailwindcss/postcss': ^4.1.14
  '@tanstack/react-devtools': ^0.7.7
  '@tanstack/react-form': ^1.23.7
  '@tanstack/react-form-devtools': ^0.1.7
  '@tanstack/react-query': ^5.90.2
  '@tanstack/react-query-devtools': ^5.90.2
  '@turbo/gen': ^2.5.8
  '@types/node': ^24.9.1
  '@types/pg': ^8.15.5
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@types/react-syntax-highlighter': ^15.5.13
  '@types/web-push': ^3.6.4
  '@vercel/analytics': ^1.5.0
  '@vercel/speed-insights': ^1.2.0
  better-auth: ^1.3.28
  class-variance-authority: ^0.7.1
  client-only: ^0.0.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  cross-env: ^10.1.0
  dotenv: ^17.2.3
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.6
  embla-carousel-react: ^8.6.0
  gray-matter: ^4.0.3
  input-otp: ^1.4.2
  jiti: ^2.4.2
  jsdom: ^27.0.0
  lefthook: ^2.0.1
  lucide-react: ^0.545.0
  motion: ^12.23.24
  next: 15.5.4
  next-mdx-remote: ^5.0.0
  next-sitemap: ^4.2.3
  next-themes: ^0.4.6
  nuqs: ^2.7.1
  pg: ^8.16.3
  playwright: ^1.56.1
  postcss: ^8.5.6
  postcss-load-config: ^6.0.1
  posthog-js: ^1.275.1
  posthog-node: ^5.9.5
  radix-ui: ^1.4.3
  react: ^19.2.0
  react-day-picker: ^9.11.1
  react-dom: ^19.2.0
  react-resizable-panels: ^3.0.6
  react-scan: ^0.4.3
  react-syntax-highlighter: ^16.0.0
  recharts: 2.15.4
  rimraf: ^6.0.1
  server-only: ^0.0.1
  sonner: ^2.0.7
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.14
  tsdown: ^0.15.8
  turbo: ^2.5.8
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  ultracite: 6.0.0
  vaul: ^1.1.2
  vitest: ^3.2.4
  zod: ^4.1.12

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - core-js
  - core-js-pure
  - esbuild
  - lefthook
  - sharp
