import type { ZapSecuritySettings } from "./types";

export const ZAP_SECURITY_CONFIG: ZapSecuritySettings = {
	CSP: {
		DEFAULT_SRC: ["'self'"],
		SCRIPT_SRC: ["'self'", "'unsafe-eval'", "'unsafe-inline'"],
		STYLE_SRC: ["'self'", "'unsafe-inline'"],
		IMG_SRC: [
			"'self'",
			"blob:",
			"data:",
			"https://www.gravatar.com",
			"https://*.googleusercontent.com",
		],
		FONT_SRC: ["'self'"],
		OBJECT_SRC: ["'none'"],
		BASE_URI: ["'self'"],
		FORM_ACTION: ["'self'"],
		FRAME_ANCESTORS: ["'none'"],
		FRAME_SRC: ["'self'", "https://www.youtube.com"],
		BLOCK_ALL_MIXED_CONTENT: false,
		UPGRADE_INSECURE_REQUESTS: true,
	},
	PERMISSIONS_POLICY: {
		CAMERA: ["self"],
		GEOLOCATION: ["self"],
		MICROPHONE: ["self"],
		PAYMENT: ["self"],
		DISPLAY_CAPTURE: ["self"],
		FULLSCREEN: ["self"],
		PICTURE_IN_PICTURE: ["self"],
		AUTOPLAY: ["self"],
		ENCRYPTED_MEDIA: ["self"],
		WEB_SHARE: ["self"],
		ACCELEROMETER: ["self"],
		GYROSCOPE: ["self"],
		MAGNETOMETER: ["self"],
		SCREEN_WAKE_LOCK: ["self"],
		GAMEPAD: [],
		HID: [],
		IDLE_DETECTION: [],
		LOCAL_FONTS: [],
		MIDI: [],
		BLUETOOTH: [],
		SERIAL: [],
		XR_SPATIAL_TRACKING: [],
		CROSS_ORIGIN_ISOLATED: [],
		PUBLICKEY_CREDENTIALS_GET: [],
		USB: [],
	},
};
