/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as WebhooksStripeRouteImport } from './routes/webhooks.stripe'
import { Route as ProtectedDashboardBillingRouteImport } from './routes/_protected.dashboard.billing'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api.stripe.checkout'
import { Route as ApiStripePortalRouteImport } from './routes/api.stripe.portal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const WebhooksStripeRoute = WebhooksStripeRouteImport.update({
  id: '/webhooks/stripe',
  path: '/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardBillingRoute =
  ProtectedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripePortalRoute = ApiStripePortalRouteImport.update({
  id: '/api/stripe/portal',
  path: '/api/stripe/portal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/webhooks/stripe': typeof WebhooksStripeRoute
  '/dashboard/billing': typeof ProtectedDashboardBillingRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/webhooks/stripe': typeof WebhooksStripeRoute
  '/dashboard/billing': typeof ProtectedDashboardBillingRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/webhooks/stripe': typeof WebhooksStripeRoute
  '/_protected/dashboard/billing': typeof ProtectedDashboardBillingRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/webhooks/stripe'
    | '/dashboard/billing'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/webhooks/stripe'
    | '/dashboard/billing'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/dashboard'
    | '/webhooks/stripe'
    | '/_protected/dashboard/billing'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  WebhooksStripeRoute: typeof WebhooksStripeRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripePortalRoute: typeof ApiStripePortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/webhooks/stripe': {
      id: '/webhooks/stripe'
      path: '/webhooks/stripe'
      fullPath: '/webhooks/stripe'
      preLoaderRoute: typeof WebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/billing': {
      id: '/_protected/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof ProtectedDashboardBillingRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/portal': {
      id: '/api/stripe/portal'
      path: '/api/stripe/portal'
      fullPath: '/api/stripe/portal'
      preLoaderRoute: typeof ApiStripePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardBillingRoute: typeof ProtectedDashboardBillingRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardBillingRoute: ProtectedDashboardBillingRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  WebhooksStripeRoute: WebhooksStripeRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripePortalRoute: ApiStripePortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
