/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ApiOgRouteImport } from './routes/api.og'
import { Route as WebhooksSplatRouteImport } from './routes/webhooks.$'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected.dashboard.index'
import { Route as ProtectedDashboardBillingRouteImport } from './routes/_protected.dashboard.billing'
import { Route as ProtectedDashboardSettingsRouteImport } from './routes/_protected.dashboard.settings'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api.stripe.checkout'
import { Route as ApiStripePortalRouteImport } from './routes/api.stripe.portal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksSplatRoute = WebhooksSplatRouteImport.update({
  id: '/webhooks/$',
  path: '/webhooks/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ProtectedDashboardBillingRoute =
  ProtectedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardSettingsRoute =
  ProtectedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripePortalRoute = ApiStripePortalRouteImport.update({
  id: '/api/stripe/portal',
  path: '/api/stripe/portal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/webhooks/$': typeof WebhooksSplatRoute
  '/dashboard/billing': typeof ProtectedDashboardBillingRoute
  '/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/api/og': typeof ApiOgRoute
  '/webhooks/$': typeof WebhooksSplatRoute
  '/dashboard/billing': typeof ProtectedDashboardBillingRoute
  '/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/webhooks/$': typeof WebhooksSplatRoute
  '/_protected/dashboard/billing': typeof ProtectedDashboardBillingRoute
  '/_protected/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/dashboard'
    | '/api/og'
    | '/webhooks/$'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/api/og'
    | '/webhooks/$'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/robots.txt'
    | '/_protected/dashboard'
    | '/api/og'
    | '/webhooks/$'
    | '/_protected/dashboard/billing'
    | '/_protected/dashboard/settings'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/_protected/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ApiOgRoute: typeof ApiOgRoute
  WebhooksSplatRoute: typeof WebhooksSplatRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripePortalRoute: typeof ApiStripePortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/$': {
      id: '/webhooks/$'
      path: '/webhooks/$'
      fullPath: '/webhooks/$'
      preLoaderRoute: typeof WebhooksSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/billing': {
      id: '/_protected/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof ProtectedDashboardBillingRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/settings': {
      id: '/_protected/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof ProtectedDashboardSettingsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/portal': {
      id: '/api/stripe/portal'
      path: '/api/stripe/portal'
      fullPath: '/api/stripe/portal'
      preLoaderRoute: typeof ApiStripePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardBillingRoute: typeof ProtectedDashboardBillingRoute
  ProtectedDashboardSettingsRoute: typeof ProtectedDashboardSettingsRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardBillingRoute: ProtectedDashboardBillingRoute,
  ProtectedDashboardSettingsRoute: ProtectedDashboardSettingsRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ApiOgRoute: ApiOgRoute,
  WebhooksSplatRoute: WebhooksSplatRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripePortalRoute: ApiStripePortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
