name: Auto Pull Request

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Create PR to main (if not exists)
        run: |
          SOURCE_BRANCH="${GITHUB_REF#refs/heads/}"
          
          COUNT=$(gh pr list \
            --state open \
            --head "$SOURCE_BRANCH" \
            --json number \
            --jq 'length')

          if [ "$COUNT" -eq 0 ]; then
            PR_URL=$(gh pr create \
              --title "$SOURCE_BRANCH → main" \
              --body "Automated PR from $SOURCE_BRANCH to main" \
              --base main \
              --head "$SOURCE_BRANCH" \
              --json url \
              --jq '.url')

            echo "Created PR: $PR_URL"
            
            gh pr edit "$PR_URL" --add-label "automated-pr"
          else
            echo "PR already exists for $SOURCE_BRANCH (any destination)."
          fi
        env:
          GH_TOKEN: ${{ secrets.ZAP_STUDIO_GH_TOKEN }}
