name: Build

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build-monorepo:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "latest"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build monorepo
        run: pnpm run build
        env:
          SKIP_ENV_VALIDATION: true
