name: Build

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build-monorepo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build monorepo
        run: bun run build
