name: Discord Notification on PR Merge
permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types:
      - closed  # fires on both merged and closed without merge

jobs:
  announce-pr-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord (Embed)
        uses: niranjanshk27/discord-notify@main
        with:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TITLE: "PR Merged"
          CONTENT: "Pull Request [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) by **${{ github.event.pull_request.user.login }}** has been merged into `${{ github.event.pull_request.base.ref }}`."
          EMBEDS: "true"
