name: Lint

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  lint-monorepo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run linter on the monorepo
        run: bun run lint
