name: Test

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  test-monorepo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun run test

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            **/coverage/**
            coverage.json
          retention-days: 7
