name: Check Types

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  check-types-monorepo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup bun
        uses: oven-sh/setup-bun@v2.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 24.2.0

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run check-types on the monorepo
        run: bun run check-types
